### ISSUE TITLE
Rename single-integration "hub" apps to integration-branded

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#1028]
Apps like Search (Algolia) or CRM (Mailchimp) are branded as "hubs," but we decided not to continue this approach. 

New apps will be written as a single-integration. Old apps should be rebranded
```[tasklist]
### Tasks
- [ ] Rebrand Search App to Algolia
- [ ] Rebrand CRM app to Mailchimp
- [ ] Rebrand Product Feed to Google Merchant Center
- [ ] Rebrand Monitoring to Datadog
```
