### ISSUE TITLE
Add monitoring for CMS app

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#1157]
```[tasklist]
### Tasks
- [ ] Set up Vercel log drain and measure resources
- [ ] Set up logger
- [ ] Set up OTEL
```
