### ISSUE TITLE
Segment.io integration

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#334]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/apps/pull/881
- [x] Cloud deployment
- [ ] https://github.com/saleor/saleor-docs/pull/873
- [x] Appstore
- [x] dependabot and labele
```

**Comment by lkostrowski** [comment]
https://github.com/saleor/apps/pull/897
