### ISSUE TITLE
Fullstack Apps setup on AWS

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#534]
Research on opt-out apps from Serverless, Vercel and Saleor Metadata 
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/apps/pull/537
- [x] Add feature that will tracking POC jobs and display to the user
- [ ] https://github.com/saleor/apps/issues/717
- [ ] https://github.com/saleor/apps/issues/719
- [ ] https://github.com/saleor/apps/issues/718
- [ ] https://github.com/saleor/apps/issues/716
- [ ] Evaluate pg-boss queue
- [ ] Implement setup with 2 queues to route short and long jobs
- [ ] Establish how workers will be added (cpu, queue?)
- [ ] Try to dynamically load config (instead env), so single deployment can be promoted without rebuilding
- [ ] Compare cloud console setup
- [ ] Evalute kysely
```
