### ISSUE TITLE
🗝️ Dynamic permissions for Apps

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#569]
This RFC is part of the *Updating Apps* epic. The goal is to deliver a set of APIs that will allow Apps to:
1. Gracefully update themselves internally by maintaining code compatible with a range of Saleor versions and Dashboards
2. Eventually lead to full "update" with Saleor orchestration.

# How an app can register permission

At the moment, there are two ways how the app can possess a Permission:
1. During installation with manifest, manifest declares permissions to be provided.
2. mutation `appUpdate` can overwrite permissions. It requires a token of a staff member with MANAGE_APPS permission

> **Warning**
> There is a bug that App can be granted with `MANAGE_APPS` permission. However, operations needing this permission will not work. See [this error](https://github.com/saleor/saleor/issues/12298)

The app also receives the frontend-side staff user token, but it is stripped and doesn't have MANAGE_APPS permission.

This outlines the problem that app can't change permission without user mutation.

# Why apps need dynamic permissions

There are 3 major reasons
1. Security - Grant only what is needed. See also [this principle](https://en.wikipedia.org/wiki/Principle_of_least_privilege)
2. Feature progression in time - allow app to enable new features without reinstalling
3. Backwards compatibility - the app will not request permission that doesn't exist yet

More details about each reason are below:

## 1. Security

Consider an abstract Messaging App. It can briefly:
1. React on any event in Saleor
2. Forward it to an external provider like Sendgrid or Slack
3. Can be configured for internal events (send Slack message when products are out of stock), external events (send order confirmation to the user) or both

Such an app requires as many permissions as many entities it requires - like `MANAGE_PRODUCTS` and `MANAGE_ORDERS`.

However, some users may want to configure only some events, like end-user orders notification, without product-related ones. In such a scenario, `MANAGE_PRODUCTS` permission is not needed, but app will be granted anyway. It has to request all permissions, so internally it can consume them, even if never enabled.

Another reason is that Saleor doesn't yet have separate permissions for READ & WRITE. That means extra cautiousness is needed when installing 3rd party apps.

### How dynamic permissions solve security problems

The app will not register any permission in the Manifest with dynamic permissions available. It can be installed to try it out, but it will not work - Saleor will forbid operations. The app can ask users to enable permissions. Also, users can remove permissions later.

## 2. Features progression

Imagine the app that sends emails to users after an order is placed. It needs `MANAGE_ORDERS` permission. The app was installed in Saleor 3.14.

Imagine that in the future, Saleor 3.17 adds new permissions, `READ_ORDERS`. It will allow querying orders, but writing will require `MANAGE_ORDERS.`

The app developer decides to use READ_ORDERS and wants to update the app. 
- Old Saleor that doesn't have this permission will not be affected - the app must verify if such permission is available. 
- the app's Manifest will be updated - no permissions will be required. It simplifies the process because the app doesn't have to verify the Saleor version on the Manifest step (to know if permissions exist).
- Apps that are installed pre-3.17 must update the permission -> **this is impossible now**.

### How dynamic permissions solve security problems

The app will prompt the user to update permissions. User will see that `MANAGE_ORDERS` permission will be removed and `READ_ORDERS` permission will be added. 

Another example can be the app just adding new features. If Saleor 3.17 adds e.g., shipping management, Messaging app can dynamically request shipping permissions to react on shipping webhooks. 

## 3. Backwards compatibility

This example is similar to the previous feature's progression but works oppositely. 

If app developers create a new app that targets, e.g., Saleor 3.17, it will cut off older Saleor versions because some APIs don't exist. 

### How dynamic permissions backward compatibility problems

The app can safely omit any permissions on the manifest level and allows it to install itself in a wide range of Saleor versions.

When the app is installed, it can show GUI with specific features that can be enabled conditionally:
- If the Saleor version is older, disable the feature and inform that update is needed
- If the Saleor version is modern, ask the user to grant permission for this feature.

# Solution

Provide API that will bridge Apps' requests through the Dashboard authorized operation to Saleor - and back.

A diagram that hopefully explains everything:

![image](https://github.com/saleor/apps/assets/9268745/2822e076-f819-4e58-bd3c-d5cc7032ee38)

### Saleor

None

### AppBridge

- new action `UpdatePermissions` with redirect URL.
- typed query params that the dashboard can construct when redirecting to the app 

Questions:
- Instead of a query URL with the result, it can also be an AppBridge event. However, this will be much harder to implement because the app will be mounted again, and the event must wait for a new handshake. Another option is using a modal instead a redirect, which will not cause the app to unmount

### App

The app must adjust its business logic when APIs are ready.

### Dashboard
- Add a dedicated view/modal with permissions listed and "approve" / "reject" buttons
- Add editable permissions list in Dashboard -> App -> Manage app. Allow removing permission there

Questions:
- Should the "Manage App" screen also allow permission to add ahead of time?
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor-dashboard/pull/3818
- [ ] https://github.com/saleor/saleor-dashboard/pull/3829
- [ ] https://github.com/saleor/saleor-app-sdk/pull/261
- [ ] https://github.com/saleor/apps/issues/694
- [ ] https://github.com/saleor/saleor-dashboard/pull/3962
```
