### ISSUE TITLE
Add Saleor Version to AppBridgeState

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#673]
Saleor version is important for app, to handle properly features, for example new webhook added in version X.

App can call Saleor to get this field, but its convenient to have this field automatically provided by Dashboard in appbridge
```[tasklist]
### Tasks
- [x] Extend handshake event to provide Saleor Version
- [ ] https://github.com/saleor/saleor-app-sdk/pull/260
- [ ] https://github.com/saleor/apps/pull/672
- [ ] https://github.com/saleor/saleor-dashboard/pull/3789
```
