### ISSUE TITLE
E&M: Support for order refund events

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/apps#728]
```[tasklist]
### Tasks
- [ ] Add subscription for ORDER_REFUNDED
- [ ] Add add example template and payload
- [ ] Make ORDER_REFUNDED available for Saleor versions >= 3.14
- [ ] Add subscription for ORDER_FULLY_REFUNDED
- [ ] Add add example template and payload
- [ ] Make ORDER_FULLY_REFUNDED available for Saleor versions >= 3.14
```

**Comment by lkostrowski** [comment]
@krzysztofwolski can we close this?

**Comment by krzysztofwolski** [comment]
Closing, functionality has been implemented. Both partial and full refund are triggering an email.
