### ISSUE TITLE
E&M: Configurable metadata filtering

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/apps#731]
Related issue: #313

Attaching all private metadata to the payload may result in exposing nonpublic information. By adding a configurable filter (regexp), users can specify which keys should be passed to templates.

```[tasklist]
### Tasks
- [ ] Add private metadata regexp form to the configuration
- [ ] Filter private metadata before passing to template engine
- [ ] Update the documentation
```
