### ISSUE TITLE
Improve Product Feed mapping

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#814]
Quotes from the users:

>The Brand field in the feed isn’t populated - we have 2 vendor fields currently, so would want to map one of those to Brand. Material and colour also doesn’t pass into the feed, and nor does product ID 

>Product type is also one we want to transfer, but not the ‘Default’ one which currently goes into the feed

```[tasklist]
### Tasks
- [x] Add mapping for additional google attributes (color, material, etc)
- [x] Extend product feed with attribute data
- [ ] Documentation
- [x] Add product grouping
```

**Comment by krzysztofwolski** [comment]
Link to the documentation PR https://github.com/saleor/saleor-docs/pull/862
