### ISSUE TITLE
Search App - mapping improvements

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#825]
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/apps/issues/755
- [ ] https://github.com/saleor/apps/issues/774
- [ ] https://github.com/saleor/apps/issues/775
- [ ] https://github.com/saleor/apps/issues/836
- [ ] https://github.com/saleor/apps/issues/863
- [ ] https://github.com/saleor/apps/issues/893
```
