### ISSUE TITLE
Plugins to Apps migration

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#837]
Group of tasks needed to officially deprecate some of the plugins
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/apps/issues/71
- [ ] Emails & Messages - migration guide doc
- [ ] Taxes - migration guide doc
- [ ] https://github.com/saleor/saleor-docs/pull/880
```
